version: '3.8'
services:
  mongo:
    image: mongo
  api:
    build: ..
    ports:
     - "8080:8080"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/test
     - BASE_URL=http://localhost:8080
    links:
     - mongo
    depends_on:
     - mongo
  web:
    build: ..
    ports:
      - "3000:3000"
    environment:
      - BASE_URL=http://localhost:3000

