development:
  db_url: "mongodb://localhost:27017/local-db"
  api_url: "http://localhost:8080"
  backend_port: 8080
  frontend_port: 3000

testing:
  db_url: "mongodb://localhost:27017/testing-db"
  api_url: "https://api.test.demo.interview"
  backend_port: 8080
  frontend_port: 3000

staging:
  db_url: "mongodb://staging.mongodb.net:27017/staging-db"
  api_url: "https://api.stg.demo.interview"
  backend_port: 8080
  frontend_port: 3000

production:
  db_url: "mongodb://prod.mongodb.net:27017/prod-db"
  api_url: "https://api.demo.interview"
  backend_port: 8080
  frontend_port: 3000
